---
title: "Chapter 9 Exercises - Guest Lecture"
author: "Christopher Tsz Hin Choi"
date: "2025-11-10"
output:
  html_document: default
  word_document: default
params:
  ufo_shape: "circle"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(
  echo = TRUE,  
  results = "markup", 
  warning = FALSE,   
  message = FALSE,
  error = FALSE    
)
```

```{r}
#set package repo----
options(repos = c("https://packagemanager.rstudio.com/all/2020-10-01+Y3JhbiwyOjI4Nzs0QzY3NkFEQQ"))
#verify package source
options('repos')
```

```{r}
ufo = read.csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2019/2019-06-25/ufo_sightings.csv')

nrow(ufo)
names(ufo)
head(ufo)

plot(x = ufo$longitude, y = ufo$latitude)
```

•  Create a new dataframe with only observations in the
United States
• convert `date_time` and `date_documented` variables to
the correct class
• generate a parameterized Rmd using the `ufo_shape`
variable
```{r}
usa_ufo = ufo |>
  dplyr::filter(country == 'us') |>
  dplyr::mutate(date_time = lubridate::mdy_hm(date_time),
                date_documented = lubridate::mdy(date_documented))
  
```


```{r}
library(tidyverse)
library(readr)
library(lubridate)
```



```{r}
ufo_sightings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")
ufo_sightings_shape <- ufo_sightings %>% 
  mutate(date_time = mdy_hm(date_time),
         sighting_year = year(date_time)) %>% 
  filter(ufo_shape == params$ufo_shape)
```

```{r}
ufo_sightings_shape %>% 
  group_by(ufo_shape) %>% 
  summarize(n_shape = n()) %>% 
  ungroup() %>% 
  ggplot() +
  geom_col(aes(x = ufo_shape, y = n_shape))
```


```{r}
#libraries----
library(tidyverse)
library(lubridate)
library(leaflet)
library(DT)
library(plotly)

#snapshot
#renv::snapshot() (only needed periodically during work)

#read in data----
ufo_sightings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-25/ufo_sightings.csv")
```

```{r}

#exercise 1----
##data manipulation
ufo_sightings_us <- ufo_sightings %>% 
  filter(country == "us") %>% 
  mutate(date_time = mdy_hm(date_time),
         date_documented = mdy(date_documented))

##parameterized Rmd (see params.Rmd)
```

```{r}
#exercise 2----
##leaflet for `encounter_length`
pal <- colorQuantile("YlOrRd", NULL, n = 8)

leaflet(ufo_sightings) %>% 
  addTiles() %>%
  addCircleMarkers(color = ~pal(encounter_length))

##plotly for `shape`

#filter to 3 shapes
ufo_sightings_shapes <- ufo_sightings %>% 
  filter(ufo_shape %in% c("circle", "fireball", "oval"))
#plot
p <- ggplot(data = ufo_sightings_shapes, aes(x = ufo_shape)) +
  geom_bar(position = "dodge")
ggplotly(p)

#DT
datatable(ufo_sightings_us, options = list(pageLength = 5))

```